# Site settings
title: Hello, world! I'm Anders
name: Anders # your name
email: peakbreaker.io@gmail.com # your email address
description: > # this means to ignore newlines until "baseurl:"
    This is where I write my daily technology insights - Here you'll find tech,
    tuts and talk from my life as an engineer.

baseurl: "/blog/"  # the subpath of your site, e.g. /blog
url: "https://peakbreaker.com" # the base hostname & protocol for your site
site-twitter: peakbreaker # your Twitter username
social-twitter: peakbreaker # add your Twitter handle
social-facebook: # add your Facebook handle
social-linkedin: anders-l-hurum # add your Linkedin handle
social-github: peakbreaker # your Github username
social-email: peakbreaker.io@gmail.com # add your Email address

# Author Settings
author: Anders L. Hurum # add your name
author-img: anders_profile.jpg # add your photo
about-author: Software engineer currently focusing on embedded systems. Hoping to get a girlfriend as beautiful as my code # add description

discus-identifier:  # your disqus username
analytics: # Google Analytics

# Build settings
permalink: ':title/'
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
