# Site settings
title: itsAnders
name: Anders # your name
email: andershurum@gmail.com # your email address
description: >
    A Simple Jekyll Blog for myself. # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://andurshurrdurr.github.io" # the base hostname & protocol for your site
twitter_username:  # your Twitter username
github_username:  # your Github username
disqus_username:  # your disqus username

debug_statement: "thisisdebug"

google-analytics:  # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
